DROP SCHEMA IF EXISTS MUSEUM;
CREATE SCHEMA MUSEUM;
USE MUSEUM;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
	U_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	ID	VARCHAR(20),
	PASSWORD	VARCHAR(40),
	NAME	VARCHAR(20),
	NICKNAME	VARCHAR(20),
	EMAIL	VARCHAR(50),
	ROLE	VARCHAR(10)	DEFAULT 'ROLE_USER',
	KAKAOTOKEN	VARCHAR(1000),
	NAVERTOKEN	VARCHAR(1000),
	GOOGLETOKEN	VARCHAR(1000)
);


SELECT * FROM USER;

DROP TABLE IF EXISTS COLLECTION;
CREATE TABLE COLLECTION (
	CT_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	U_NO	INT,
	CT_Title	VARCHAR(500),
	CT_CONTENT	VARCHAR(2000),
	CT_Status	VARCHAR(3)
);

SELECT * FROM COLLECTION;

DROP TABLE IF EXISTS HERITAGE;
-- delete from heritage;
-- truncate heritage;
CREATE TABLE HERITAGE (
	H_NO	INT AUTO_INCREMENT PRIMARY KEY,
	ccmaName	VARCHAR(500), -- 문화재종목
	ccbaMnm1	VARCHAR(500), -- 문화재명
	gcodeName	VARCHAR(500), -- 문화재분류
	bcodeName	VARCHAR(500), -- 문화재분류2
	mcodeName	VARCHAR(500), -- 문화재분류3
	scodeName	VARCHAR(500), -- 문화재분류4
	ccbaQuan	VARCHAR(500), -- 수량
	ccbaAsdt	VARCHAR(500), -- 지정(등록일)
	ccbaCtcdNm	VARCHAR(500), -- 시도명
	ccsiName	VARCHAR(500), -- 시군구명
	ccbaLcad	VARCHAR(500), -- 소재지 상세
	ccceName	VARCHAR(500), -- 시대
	ccbaPoss	VARCHAR(500), -- 소유자
	longitude	VARCHAR(500), -- 경도 ( 0일 경우 : 위치 값 없음 )
	latitude	VARCHAR(500), -- 위도 ( 0일 경우 : 위치 값 없음 )
	ccbaAdmin	VARCHAR(500), -- 관리자
	imageUrl	VARCHAR(500), -- 메인노출이미지URL
	content	VARCHAR(5000) -- 내용
);

SELECT * FROM HERITAGE;
select * from HERITAGE where H_NO = 1;

DROP TABLE IF EXISTS HERITAGE_IMAGE;
CREATE TABLE HERITAGE_IMAGE (
	HI_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	H_NO	INT,
	ImageUrl1	VARCHAR(500),
	CcimDesc1	VARCHAR(500),
    ImageUrl2	VARCHAR(500),
	CcimDesc2	VARCHAR(500),
    ImageUrl3	VARCHAR(500),
	CcimDesc3	VARCHAR(500),
    ImageUrl4	VARCHAR(500),
	CcimDesc4	VARCHAR(500)
);

SELECT * FROM HERITAGE_IMAGE;

DROP TABLE IF EXISTS HERITAGE_RE;
CREATE TABLE HERITAGE_RE (
	HR_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	H_NO	INT,
	U_NO	INT,
	HR_CONTENT	VARCHAR(2000),
	HR_CREATE_DATE	DATETIME,
	HR_MODIFY_DATE	DATETIME
);

SELECT * FROM HERITAGE_RE;

DROP TABLE IF EXISTS BOARD;
CREATE TABLE BOARD (
	B_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	U_NO	INT,
	TITLE	VARCHAR(1000),
	CONTENT	VARCHAR(2000),
	TYPE	VARCHAR(100),
	ORIGINAL_FILENAME	VARCHAR(1000),
	RENAMED_FILENAME	VARCHAR(1000),
	READCOUNT	INT,
	STATUS	VARCHAR(3) DEFAULT 'Y',
	CREATE_DATE	DATETIME,
	MODIFY_DATE	DATETIME	
);

SELECT * FROM BOARD;

DROP TABLE IF EXISTS BOARD_RE;
CREATE TABLE BOARD_RE (
	BR_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	B_NO	INT,
	U_NO	INT,
	BR_CONTENT	VARCHAR(2000),
	BR_CREATE_DATE	DATETIME,
	BR_MODIFY_DATE	DATETIME,
	BR_STATUS	VARCHAR(3)
);

SELECT * FROM BOARD_RE;

DROP TABLE IF EXISTS COLLECTION_RE;
CREATE TABLE COLLECTION_RE (
	CTR_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	CT_NO	INT,
	U_NO	INT,
	CTR_CONTENT	VARCHAR(2000),
	CTR_CREATE_DATE	DATETIME,
	CTR_MODIFY_DATE	DATETIME,
	CTR_STATUS	VARCHAR(3)
);

SELECT * FROM COLLECTION_RE;

DROP TABLE IF EXISTS STAMP;
CREATE TABLE STAMP (
	S_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	U_NO	INT,
	SINLA	INT,
	BEKJE	INT,
	GOGURYEO	INT
);

SELECT * FROM STAMP;

DROP TABLE IF EXISTS COLLECTION_LIKE;
CREATE TABLE COLLECTION_LIKE (
	CTL_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	CT_NO	INT,
	U_NO	INT,
	CTL_LIKE	INT
);

SELECT * FROM COLLECTION_LIKE;

DROP TABLE IF EXISTS COLLECTION_INPUT_H;
CREATE TABLE COLLECTION_INPUT_H (
	CT_NO	INT	AUTO_INCREMENT PRIMARY KEY,
	H_NO	INT
);

SELECT * FROM COLLECTION_INPUT_H;

DROP TABLE IF EXISTS EVENT;
CREATE TABLE EVENT (
	E_NO	INT	PRIMARY KEY,
	subTitle	VARCHAR(500),
	subContent	VARCHAR(2000),
	sDate	VARCHAR(500),
	eDate	VARCHAR(500),
	subDesc	VARCHAR(500),
	subDesc1	VARCHAR(500),
	image	VARCHAR(2000),
	sido	VARCHAR(100),
	gogun	VARCHAR(100),
	subDate	VARCHAR(2000)
);

INSERT INTO EVENT VALUES(1,'종가의 정성','종부에게 배우는 종가의 음식을 알아보고 체험해 보는 프로그램' ,20221101 ,20221101, '의정공김국광종택','일반인','미정','충청남도', '논산시','11월1일-8일-15일-22일 매주 화요일 오전 09:30~12:30');
INSERT INTO EVENT VALUES(2,'에헴! 이리오너라 향교나들이','향교나들이를 통해 전통예절을 배우고 익히는 인성교육의 전당' ,20221101 ,20221101, '영천향교',' 어린이집 어린이','미정','경상북도', '영천시 ','11/1, 11/8, 11/15, 11/22, 11/29 (09:00~14:00) 화요일');
INSERT INTO EVENT VALUES(3,'찾아가는향교',' 인성예절 및 전통놀이' ,20221101 ,20221101, '장애인작업장, 지역아동센터','장애인 및 초등학생','미정','강원도 ', '정선군 ',' 11/1, 11/2, 11/3, 11/8, 11/9, 11/10, 11/15, 11/16, 11/17 (총 9회) // 11:00~18:00 ');
INSERT INTO EVENT VALUES(4,'법고창신 전통문화체험','예절, 한복입기,한옥, 전통혼례, 국궁, 투호, 덕메치기, 윷놀리, 다도, 야행 ' ,20221101 ,20221101, '경주향교','일반시민 ','미정','경상북도 ', '경주시 ','11/2, 11/8, 11/9, 11/14, 11/16, 11/18');
INSERT INTO EVENT VALUES(5,'양주향교와 함께하는 시간여행','종양주향교 해설사의 안내를 통해 향교와 인근 역사문화유산 체험 및 탐방' ,20221101 ,20221101, '양주향교','시민','미정','경기도 ', '양주시 ',' 11/2, 11/5, 11/9, 11/12, 11/16, 11/23, 11/26, 11/30 (총 9회) // 10:00~16:00 ');
SELECT * FROM EVENT;

ALTER TABLE COLLECTION ADD CONSTRAINT FK_USER_TO_COLLECTION_1 FOREIGN KEY (
	U_NO
)
REFERENCES USER (
	U_NO
);

ALTER TABLE HERITAGE_IMAGE ADD CONSTRAINT FK_HERITAGE_TO_HERITAGE_IMAGE_1 FOREIGN KEY (
	H_NO
)
REFERENCES HERITAGE (
	H_NO
);

ALTER TABLE BOARD ADD CONSTRAINT FK_USER_TO_BOARD_1 FOREIGN KEY (
	U_NO
)
REFERENCES USER (
	U_NO
);

ALTER TABLE BOARD_RE ADD CONSTRAINT FK_BOARD_TO_BOARD_RE_1 FOREIGN KEY (
	B_NO
)
REFERENCES BOARD (
	B_NO
);

ALTER TABLE BOARD_RE ADD CONSTRAINT FK_USER_TO_BOARD_RE_1 FOREIGN KEY (
	U_NO
)
REFERENCES USER (
	U_NO
);

ALTER TABLE COLLECTION_RE ADD CONSTRAINT FK_COLLECTION_TO_COLLECTION_RE_1 FOREIGN KEY (
	CT_NO
)
REFERENCES COLLECTION (
	CT_NO
);

ALTER TABLE COLLECTION_RE ADD CONSTRAINT FK_USER_TO_COLLECTION_RE_1 FOREIGN KEY (
	U_NO
)
REFERENCES USER (
	U_NO
);

ALTER TABLE STAMP ADD CONSTRAINT FK_USER_TO_STAMP_1 FOREIGN KEY (
	U_NO
)
REFERENCES USER (
	U_NO
);

ALTER TABLE COLLECTION_LIKE ADD CONSTRAINT FK_COLLECTION_TO_COLLECTION_LIKE_1 FOREIGN KEY (
	CT_NO
)
REFERENCES COLLECTION (
	CT_NO
);

ALTER TABLE COLLECTION_LIKE ADD CONSTRAINT FK_USER_TO_COLLECTION_LIKE_1 FOREIGN KEY (
	U_NO
)
REFERENCES USER (
	U_NO
);

ALTER TABLE HERITAGE_RE ADD CONSTRAINT FK_HERITAGE_TO_HERITAGE_RE_1 FOREIGN KEY (
	H_NO
)
REFERENCES HERITAGE (
	H_NO
);

ALTER TABLE HERITAGE_RE ADD CONSTRAINT FK_USER_TO_HERITAGE_RE_1 FOREIGN KEY (
	U_NO
)
REFERENCES USER (
	U_NO
);

ALTER TABLE COLLECTION_INPUT_H ADD CONSTRAINT FK_COLLECTION_TO_COLLECTION_INPUT_H_1 FOREIGN KEY (
	CT_NO
)
REFERENCES COLLECTION (
	CT_NO
);

ALTER TABLE COLLECTION_INPUT_H ADD CONSTRAINT FK_HERITAGE_TO_COLLECTION_INPUT_H_1 FOREIGN KEY (
	H_NO
)
REFERENCES HERITAGE (
	H_NO
);